version: '3.9'
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 3010:3010

  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: invoice

    volumes:
      - ./data/postgres:/var/lib/postgresql/data

    ports:
      - 5432:5432
