name: publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.ACTOR }}
          password: ${{ secrets.INVOICE_APP_PAT }}

      - name: Frontend - Build and push image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: "./frontend"
          file: "./frontend/Dockerfile"
          tags: ghcr.io/pscldev/invoice_app__frontend:latest

      - name: Backend - Build and push image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: "./backend"
          file: "./backend/Dockerfile"
          tags: ghcr.io/pscldev/invoice_app__backend:latest
      